-- AlterTable
ALTER TABLE `reception_data` 
  MODIFY `maleStatus` ENUM('NORMAL', 'LEGAL_INVITATION', 'NOT_EXIST', 'OUT_OF_COUNTRY', 'OUT_OF_PROVINCE') NOT NULL DEFAULT 'NORMAL',
  MODIFY `femaleStatus` ENUM('NORMAL', 'LEGAL_INVITATION', 'NOT_EXIST', 'OUT_OF_COUNTRY', 'OUT_OF_PROVINCE') NOT NULL DEFAULT 'NORMAL';

