-- AlterTable
ALTER TABLE `reception_data` 
  ADD COLUMN `maleStatus` ENUM('NORMAL', 'LEGAL_INVITATION', 'OUT_OF_COUNTRY', 'OUT_OF_PROVINCE') NOT NULL DEFAULT 'NORMAL',
  ADD COLUMN `femaleStatus` ENUM('NORMAL', 'LEGAL_INVITATION', 'OUT_OF_COUNTRY', 'OUT_OF_PROVINCE') NOT NULL DEFAULT 'NORMAL',
  ADD COLUMN `maleBirthPlace` VARCHAR(255) NULL,
  ADD COLUMN `maleRegistration` VARCHAR(255) NULL,
  ADD COLUMN `maleCountry` VARCHAR(255) NULL,
  ADD COLUMN `femaleBirthPlace` VARCHAR(255) NULL,
  ADD COLUMN `femaleRegistration` VARCHAR(255) NULL,
  ADD COLUMN `femaleCountry` VARCHAR(255) NULL,
  MODIFY `maleName` VARCHAR(255) NULL,
  MODIFY `maleLastName` VARCHAR(255) NULL,
  MODIFY `maleFatherName` VARCHAR(255) NULL,
  MODIFY `maleBirthDate` DATETIME NULL,
  MODIFY `maleNationalId` VARCHAR(255) NULL,
  MODIFY `maleAge` INT NULL,
  MODIFY `femaleName` VARCHAR(255) NULL,
  MODIFY `femaleLastName` VARCHAR(255) NULL,
  MODIFY `femaleFatherName` VARCHAR(255) NULL,
  MODIFY `femaleBirthDate` DATETIME NULL,
  MODIFY `femaleNationalId` VARCHAR(255) NULL,
  MODIFY `femaleAge` INT NULL;

